baseURL = "https://volcanolair.co/"
languageCode = "en-us"
title = "Volcano Lair"
theme = "hello-friend-ng"
googleAnalytics = "G-WG01CH0XM7"
disqusShortname = 'volcano-lair'


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  custom_css 	  = ["css/styles.css"]

  # Subtitle for home
  homeSubtitle = "We Make Games"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Homepage for Volcano Lair, an indie game studio that's trying its best."
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Volcano Lair"
    subtitle = "We Make Games"
    keywords = ""
    copyright = '&copy; 2016-2023 Volcano Lair'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      path = "/img/logo.svg"
      path_light = "/img/logo-black.svg"
      alt = "Volcano Lair"

    [languages.en.params.footer]
      copyright = "Volcano Lair LLC"
      privacy = "yes"
      terms = "yes"
      # streaming = "yes"
      discord = "yes"
      forums = "yes"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
	
#  [[menu.main]]
#    identifier = "jobs"
#    name       = "Careers"
#    url        = "/jobs/"
	
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts/"

  [[menu.main]]
	  identifier = "contact"
    name       = "Contact"
    url        = "/contact/"

  [[menu.main]]
	  identifier = "forums"
    name       = "Forums"
    url        = "https://forums.volcanolair.co"
	
[[params.social]]
 url = "//gamedev.social/@volcanolair"
 name = "mastodon"
 description = "Volcano Lair Mastodon page"

[[params.social]]
 url = "//twitter.com/thevolcanolair"
 name = "twitter"
 description = "Why would you want to follow us on Twitter"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
